### ISSUE TITLE
How to generate the `hxb2_annotated_SpecialSites_ByCodon` file?

### ISSUE THREAD

**Issue by liamxg** [ChrisHIV/hiv_vb_variant#2]
Dear @ChrisHIV,

Could I know how to generate the hxb2_annotated_SpecialSites_ByCodon file? Thanks.

**Comment by ChrisHIV** [comment]
Inside `data_external`

**Comment by liamxg** [comment]
Dear @ChrisHIV,

I know it in the `data_external` folder, but how to generate it if I want to use my own data, thanks.

**Comment by ChrisHIV** [comment]
I generated this mostly manually I'm afraid - no code to share - starting from the Los Alamos annotated HXB2 available via [here](https://www.hiv.lanl.gov/content/sequence/TUTORIALS/Tutorials.html) specifically [here](https://www.hiv.lanl.gov/content/sequence/HIV/MAP/hxb2.xls)
